jwt:
    algorithm: HS512
    secret: ${JWT_SECRET}
    validMinutes: 10
server:
    port: 8082
spring:
    datasource:
        password: 477e7fd79d528c0a6d436f5fc3f47a76bb54aa9ef07fed91c67bf43c2f9f4c3f
        url: jdbc:postgresql://ec2-54-220-53-223.eu-west-1.compute.amazonaws.com:5432/d3han8hkq49ogh
        username: zdzitimnurhmkf
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    mvc:
        throw-exception-if-no-handler-found: true
    web:
        resources:
            add-mappings: false